language: python
python:
  - 2.7

services:
  - docker
env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
        - REPO=dongen/alpine-php-nginx

install:
  - docker build -t php .
  - docker run -d -p 127.0.0.1:80:80 --name nginx-php-fpm php

script:
  - docker ps
  - sleep 5
  - curl -I 127.0.0.1:80
  - docker --version
  - export TAG="latest"
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
#  - python .travis/tests.py
