language: python
python:
  - 2.7

services:
  - docker
env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
        - REPO=dongen/php-nginx-alpine

install:
  - docker build -t php .
  - docker run -d -p 127.0.0.1:80:80 --name php-nginx-alpine php

script:
  - docker ps
  - sleep 5
  - curl -I 127.0.0.1:80
  - docker --version
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
#  - python .travis/tests.py
